// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/calendar.proto

package calendar

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_319e4b398a4282cb, []int{0}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type Calendar struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	Userid               string   `protobuf:"bytes,3,opt,name=userid,proto3" json:"userid,omitempty" bson:"userid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Calendar) Reset()         { *m = Calendar{} }
func (m *Calendar) String() string { return proto.CompactTextString(m) }
func (*Calendar) ProtoMessage()    {}
func (*Calendar) Descriptor() ([]byte, []int) {
	return fileDescriptor_319e4b398a4282cb, []int{1}
}
func (m *Calendar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calendar.Unmarshal(m, b)
}
func (m *Calendar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calendar.Marshal(b, m, deterministic)
}
func (m *Calendar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calendar.Merge(m, src)
}
func (m *Calendar) XXX_Size() int {
	return xxx_messageInfo_Calendar.Size(m)
}
func (m *Calendar) XXX_DiscardUnknown() {
	xxx_messageInfo_Calendar.DiscardUnknown(m)
}

var xxx_messageInfo_Calendar proto.InternalMessageInfo

func (m *Calendar) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Calendar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Calendar) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type CalendarResponse struct {
	Status               string    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Calendar             *Calendar `protobuf:"bytes,2,opt,name=calendar,proto3" json:"calendar,omitempty"`
	Error                string    `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *CalendarResponse) Reset()         { *m = CalendarResponse{} }
func (m *CalendarResponse) String() string { return proto.CompactTextString(m) }
func (*CalendarResponse) ProtoMessage()    {}
func (*CalendarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_319e4b398a4282cb, []int{2}
}
func (m *CalendarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalendarResponse.Unmarshal(m, b)
}
func (m *CalendarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalendarResponse.Marshal(b, m, deterministic)
}
func (m *CalendarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalendarResponse.Merge(m, src)
}
func (m *CalendarResponse) XXX_Size() int {
	return xxx_messageInfo_CalendarResponse.Size(m)
}
func (m *CalendarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalendarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalendarResponse proto.InternalMessageInfo

func (m *CalendarResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CalendarResponse) GetCalendar() *Calendar {
	if m != nil {
		return m.Calendar
	}
	return nil
}

func (m *CalendarResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type FincByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *FincByIdRequest) Reset()         { *m = FincByIdRequest{} }
func (m *FincByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FincByIdRequest) ProtoMessage()    {}
func (*FincByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_319e4b398a4282cb, []int{3}
}
func (m *FincByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FincByIdRequest.Unmarshal(m, b)
}
func (m *FincByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FincByIdRequest.Marshal(b, m, deterministic)
}
func (m *FincByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FincByIdRequest.Merge(m, src)
}
func (m *FincByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FincByIdRequest.Size(m)
}
func (m *FincByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FincByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FincByIdRequest proto.InternalMessageInfo

func (m *FincByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EventRangeRequest struct {
	Start                time.Time `protobuf:"bytes,4,opt,name=start,proto3,stdtime" json:"start" bson:"start"`
	End                  time.Time `protobuf:"bytes,5,opt,name=end,proto3,stdtime" json:"end" bson:"end"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *EventRangeRequest) Reset()         { *m = EventRangeRequest{} }
func (m *EventRangeRequest) String() string { return proto.CompactTextString(m) }
func (*EventRangeRequest) ProtoMessage()    {}
func (*EventRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_319e4b398a4282cb, []int{4}
}
func (m *EventRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRangeRequest.Unmarshal(m, b)
}
func (m *EventRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRangeRequest.Marshal(b, m, deterministic)
}
func (m *EventRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRangeRequest.Merge(m, src)
}
func (m *EventRangeRequest) XXX_Size() int {
	return xxx_messageInfo_EventRangeRequest.Size(m)
}
func (m *EventRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRangeRequest proto.InternalMessageInfo

func (m *EventRangeRequest) GetStart() time.Time {
	if m != nil {
		return m.Start
	}
	return time.Time{}
}

func (m *EventRangeRequest) GetEnd() time.Time {
	if m != nil {
		return m.End
	}
	return time.Time{}
}

type EventUpdateRequest struct {
	Updatetype           int32    `protobuf:"varint,1,opt,name=updatetype,proto3" json:"updatetype,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *EventUpdateRequest) Reset()         { *m = EventUpdateRequest{} }
func (m *EventUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*EventUpdateRequest) ProtoMessage()    {}
func (*EventUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_319e4b398a4282cb, []int{5}
}
func (m *EventUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventUpdateRequest.Unmarshal(m, b)
}
func (m *EventUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventUpdateRequest.Marshal(b, m, deterministic)
}
func (m *EventUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUpdateRequest.Merge(m, src)
}
func (m *EventUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_EventUpdateRequest.Size(m)
}
func (m *EventUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventUpdateRequest proto.InternalMessageInfo

func (m *EventUpdateRequest) GetUpdatetype() int32 {
	if m != nil {
		return m.Updatetype
	}
	return 0
}

func (m *EventUpdateRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type EventRangeResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *EventRangeResponse) Reset()         { *m = EventRangeResponse{} }
func (m *EventRangeResponse) String() string { return proto.CompactTextString(m) }
func (*EventRangeResponse) ProtoMessage()    {}
func (*EventRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_319e4b398a4282cb, []int{6}
}
func (m *EventRangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRangeResponse.Unmarshal(m, b)
}
func (m *EventRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRangeResponse.Marshal(b, m, deterministic)
}
func (m *EventRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRangeResponse.Merge(m, src)
}
func (m *EventRangeResponse) XXX_Size() int {
	return xxx_messageInfo_EventRangeResponse.Size(m)
}
func (m *EventRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventRangeResponse proto.InternalMessageInfo

func (m *EventRangeResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type EventResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Event                *Event   `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_319e4b398a4282cb, []int{7}
}
func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (m *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(m, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

func (m *EventResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *EventResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *EventResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type Event struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Title                string        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty" bson:"title"`
	Userid               string        `protobuf:"bytes,3,opt,name=userid,proto3" json:"userid,omitempty" bson:"userid"`
	Start                time.Time     `protobuf:"bytes,4,opt,name=start,proto3,stdtime" json:"start" bson:"start"`
	End                  time.Time     `protobuf:"bytes,5,opt,name=end,proto3,stdtime" json:"end" bson:"end"`
	Duration             time.Duration `protobuf:"bytes,6,opt,name=duration,proto3,stdduration" json:"duration" bson:"duration"`
	Recurring            bool          `protobuf:"varint,7,opt,name=recurring,proto3" json:"recurring,omitempty" bson:"recurring"`
	Allday               bool          `protobuf:"varint,8,opt,name=allday,proto3" json:"allday,omitempty" bson:"allday"`
	Rrule                string        `protobuf:"bytes,9,opt,name=rrule,proto3" json:"rrule,omitempty" bson:"rrule"`
	Exrule               string        `protobuf:"bytes,10,opt,name=exrule,proto3" json:"exrule,omitempty" bson:"exrule"`
	Exdates              []time.Time   `protobuf:"bytes,11,rep,name=exdates,proto3,stdtime" json:"exdates" bson:"exdates"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_319e4b398a4282cb, []int{8}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *Event) GetStart() time.Time {
	if m != nil {
		return m.Start
	}
	return time.Time{}
}

func (m *Event) GetEnd() time.Time {
	if m != nil {
		return m.End
	}
	return time.Time{}
}

func (m *Event) GetDuration() time.Duration {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Event) GetRecurring() bool {
	if m != nil {
		return m.Recurring
	}
	return false
}

func (m *Event) GetAllday() bool {
	if m != nil {
		return m.Allday
	}
	return false
}

func (m *Event) GetRrule() string {
	if m != nil {
		return m.Rrule
	}
	return ""
}

func (m *Event) GetExrule() string {
	if m != nil {
		return m.Exrule
	}
	return ""
}

func (m *Event) GetExdates() []time.Time {
	if m != nil {
		return m.Exdates
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyResponse)(nil), "calendar.EmptyResponse")
	proto.RegisterType((*Calendar)(nil), "calendar.Calendar")
	proto.RegisterType((*CalendarResponse)(nil), "calendar.CalendarResponse")
	proto.RegisterType((*FincByIdRequest)(nil), "calendar.FincByIdRequest")
	proto.RegisterType((*EventRangeRequest)(nil), "calendar.EventRangeRequest")
	proto.RegisterType((*EventUpdateRequest)(nil), "calendar.EventUpdateRequest")
	proto.RegisterType((*EventRangeResponse)(nil), "calendar.EventRangeResponse")
	proto.RegisterType((*EventResponse)(nil), "calendar.EventResponse")
	proto.RegisterType((*Event)(nil), "calendar.Event")
}

func init() { proto.RegisterFile("proto/calendar.proto", fileDescriptor_319e4b398a4282cb) }

var fileDescriptor_319e4b398a4282cb = []byte{
	// 760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0x13, 0x49,
	0x10, 0x5e, 0xc7, 0x1e, 0xc7, 0x2e, 0x6f, 0x6c, 0xa7, 0x15, 0x65, 0x27, 0x4e, 0x94, 0xc9, 0xf6,
	0x6a, 0x77, 0xc3, 0x01, 0x5b, 0x0a, 0x07, 0x24, 0x24, 0x10, 0x38, 0x0e, 0x11, 0x70, 0x41, 0x0d,
	0x9c, 0x38, 0xc0, 0xd8, 0x53, 0x98, 0x91, 0xec, 0x19, 0xd3, 0xd3, 0x13, 0xc5, 0x3c, 0x05, 0x47,
	0x5e, 0x80, 0x77, 0xe1, 0x29, 0xcc, 0x85, 0x07, 0x40, 0x7e, 0x02, 0x34, 0x5d, 0x3d, 0xe3, 0x1f,
	0x4c, 0x7e, 0x38, 0x71, 0x9b, 0xae, 0xfa, 0xea, 0xeb, 0xaa, 0xaf, 0xaa, 0x6b, 0x60, 0x6b, 0x24,
	0x43, 0x15, 0xb6, 0x7a, 0xee, 0x00, 0x03, 0xcf, 0x95, 0x4d, 0x7d, 0x64, 0xa5, 0xf4, 0xdc, 0x70,
	0xfa, 0x61, 0xd8, 0x1f, 0x60, 0x4b, 0xdb, 0xbb, 0xf1, 0x9b, 0x96, 0xf2, 0x87, 0x18, 0x29, 0x77,
	0x38, 0x22, 0x68, 0x63, 0x7f, 0x19, 0xe0, 0xc5, 0xd2, 0x55, 0x7e, 0x18, 0x18, 0xff, 0xcd, 0xbe,
	0xaf, 0xde, 0xc6, 0xdd, 0x66, 0x2f, 0x1c, 0xb6, 0xfa, 0x61, 0x3f, 0x9c, 0x01, 0x93, 0x13, 0xdd,
	0x9e, 0x7c, 0x11, 0x9c, 0xd7, 0x60, 0xe3, 0x64, 0x38, 0x52, 0x63, 0x81, 0xd1, 0x28, 0x0c, 0x22,
	0xe4, 0xef, 0xa1, 0x74, 0x6c, 0x92, 0x61, 0xfb, 0xb0, 0xe6, 0x7b, 0x76, 0xee, 0x20, 0x77, 0x58,
	0x6e, 0x57, 0xa7, 0x13, 0x07, 0xba, 0x51, 0x18, 0xdc, 0xe1, 0xaf, 0x7c, 0x8f, 0x8b, 0x35, 0xdf,
	0x63, 0xff, 0x40, 0x21, 0x70, 0x87, 0x68, 0xaf, 0x69, 0x44, 0x6d, 0x3a, 0x71, 0x2a, 0x84, 0x48,
	0xac, 0x5c, 0x68, 0x27, 0xbb, 0x01, 0xc5, 0x38, 0x42, 0xe9, 0x7b, 0x76, 0x5e, 0xc3, 0x36, 0xa7,
	0x13, 0x67, 0x83, 0x60, 0x64, 0xe7, 0xc2, 0x00, 0xf8, 0x08, 0xea, 0xe9, 0xdd, 0x69, 0x3e, 0x6c,
	0x1b, 0x8a, 0x91, 0x72, 0x55, 0x1c, 0x51, 0x1e, 0xc2, 0x9c, 0x58, 0x13, 0x32, 0xd1, 0xf4, 0xfd,
	0x95, 0x23, 0xd6, 0xcc, 0x54, 0xcd, 0x58, 0x32, 0x0c, 0xdb, 0x02, 0x0b, 0xa5, 0x0c, 0x25, 0x65,
	0x21, 0xe8, 0xc0, 0xff, 0x86, 0xda, 0x43, 0x3f, 0xe8, 0xb5, 0xc7, 0x8f, 0x3c, 0x81, 0xef, 0x62,
	0x8c, 0x14, 0xab, 0xce, 0x8a, 0x4e, 0x8a, 0xe4, 0x9f, 0x72, 0xb0, 0x79, 0x72, 0x86, 0x81, 0x12,
	0x6e, 0xd0, 0xc7, 0x14, 0xf5, 0x18, 0xac, 0x48, 0xb9, 0x52, 0xd9, 0x05, 0x7d, 0x77, 0xa3, 0x49,
	0x6d, 0x69, 0xa6, 0x6a, 0x37, 0x9f, 0xa7, 0x7d, 0x6b, 0xdb, 0x9f, 0x27, 0xce, 0x1f, 0xd3, 0x89,
	0xf3, 0x27, 0x15, 0xad, 0xc3, 0xf8, 0x87, 0x2f, 0x4e, 0x4e, 0x10, 0x05, 0xeb, 0x40, 0x1e, 0x03,
	0xcf, 0xb6, 0x2e, 0x65, 0xda, 0x36, 0x4c, 0xa6, 0x0f, 0x18, 0x78, 0xc4, 0x93, 0x84, 0xf3, 0x97,
	0xc0, 0x74, 0x9a, 0x2f, 0x46, 0x9e, 0xab, 0xb2, 0x3c, 0xf7, 0x01, 0x62, 0x6d, 0x50, 0xe3, 0x11,
	0xea, 0xaa, 0x2c, 0x31, 0x67, 0x61, 0xff, 0x82, 0x85, 0x49, 0x94, 0xd1, 0xb0, 0x36, 0xd3, 0x90,
	0x6a, 0x26, 0x2f, 0xbf, 0x6b, 0xc8, 0x8d, 0x06, 0xa6, 0x37, 0xff, 0x43, 0x51, 0xbb, 0x93, 0xde,
	0xe4, 0x57, 0x45, 0x1b, 0x37, 0x7f, 0x0d, 0x1b, 0x64, 0x58, 0xdd, 0x55, 0x2b, 0xeb, 0x6a, 0x1d,
	0xf2, 0x28, 0xa9, 0xa1, 0x65, 0x91, 0x7c, 0xce, 0x12, 0xcc, 0x5f, 0x98, 0xe0, 0xd7, 0x02, 0x58,
	0xda, 0x70, 0xe9, 0xd0, 0xfe, 0x07, 0x96, 0xf2, 0xd5, 0x20, 0x9d, 0xda, 0xfa, 0xac, 0x33, 0xda,
	0xcc, 0x05, 0xb9, 0xaf, 0x31, 0xb7, 0xbf, 0xdf, 0x30, 0x30, 0x01, 0xa5, 0x74, 0x2f, 0xd8, 0x45,
	0x4d, 0xb5, 0xf3, 0x03, 0x55, 0xc7, 0x00, 0xda, 0xbb, 0x86, 0xa9, 0x46, 0x4c, 0x69, 0x20, 0xff,
	0x98, 0xd0, 0x65, 0x3c, 0xec, 0x08, 0xca, 0x12, 0x7b, 0xb1, 0x94, 0x7e, 0xd0, 0xb7, 0xd7, 0x0f,
	0x72, 0x87, 0xa5, 0xf6, 0xd6, 0x74, 0xe2, 0xd4, 0x29, 0x2a, 0x73, 0x71, 0x31, 0x83, 0x25, 0x22,
	0xba, 0x83, 0x81, 0xe7, 0x8e, 0xed, 0x92, 0x0e, 0x98, 0x13, 0x91, 0xec, 0x5c, 0x18, 0x40, 0xd2,
	0x17, 0x29, 0xe3, 0x01, 0xda, 0xe5, 0xe5, 0xbe, 0x68, 0x33, 0x17, 0xe4, 0x4e, 0x28, 0xf1, 0x5c,
	0x03, 0x61, 0xb9, 0x2f, 0x64, 0xe7, 0xc2, 0x00, 0xd8, 0x53, 0x58, 0xc7, 0xf3, 0x64, 0xd4, 0x23,
	0xbb, 0xa2, 0x07, 0xf4, 0x22, 0x3d, 0x1b, 0x46, 0x85, 0x6a, 0xca, 0xa5, 0x03, 0x49, 0xd3, 0x94,
	0xe6, 0xe8, 0x5b, 0x01, 0x6a, 0xe9, 0x72, 0x79, 0x86, 0xf2, 0xcc, 0xef, 0x21, 0xbb, 0x0f, 0xd5,
	0x63, 0x89, 0xae, 0xc2, 0x6c, 0x6f, 0xae, 0xd8, 0x44, 0x8d, 0xc6, 0x8a, 0xed, 0x94, 0xbe, 0x86,
	0x0e, 0x54, 0x4e, 0x51, 0x65, 0xe1, 0x3b, 0x33, 0xe8, 0xd2, 0x72, 0xba, 0x84, 0xa5, 0x2a, 0x70,
	0x18, 0x9e, 0xe1, 0x55, 0x88, 0xfe, 0x9a, 0x7b, 0x47, 0xf3, 0xfb, 0x3f, 0xa9, 0x86, 0x36, 0xc8,
	0x2f, 0x57, 0x73, 0x1b, 0x2a, 0xa4, 0x07, 0xbd, 0xc7, 0xe5, 0x17, 0xbb, 0x70, 0xf5, 0xc2, 0x52,
	0xb8, 0x07, 0xa5, 0x53, 0x54, 0x14, 0x75, 0xc5, 0xd4, 0x17, 0xe2, 0x3b, 0x50, 0xa1, 0xd4, 0x89,
	0x62, 0x6f, 0x09, 0xb7, 0xb0, 0x18, 0x7f, 0xce, 0xf2, 0x00, 0x2a, 0x24, 0xe3, 0xb5, 0x12, 0x59,
	0xd0, 0xf0, 0x09, 0x54, 0xd3, 0x42, 0x22, 0xbd, 0x31, 0xd9, 0xee, 0xf2, 0x6d, 0x73, 0xff, 0x92,
	0xc6, 0xde, 0x6a, 0x27, 0x91, 0x75, 0x8b, 0x7a, 0x56, 0x6f, 0x7d, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0xc1, 0x04, 0xc9, 0xce, 0x3a, 0x08, 0x00, 0x00,
}
